site_name: "Documentation - Let's Employ"
site_description: "Let's Employ is a community-driven effort to create an open standard for publishing job listings in a structured format, making it easier for job seekers and employers to connect."
site_url: https://docs.letsemploy.org/

repo_url: https://github.com/letsemploy/docs
edit_uri: edit/main/docs/

nav:
  - Intro: index.md
  - Overview:
    - Why: overview/why.md
    - Our Approach: overview/approach.md
    - How It Works: overview/how-it-works.md
    - FAQ: overview/faq.md
    - Project: overview/project.md

  - Quickstart:
    - Into: quickstart/index.md
    - Requirements: quickstart/requirements.md
    - OJobPub: quickstart/create.md
    - Publish: quickstart/publish.md
    - Let us Know: quickstart/let-us-know.md
    - Spread the Word: quickstart/spread-the-word.md

  - OJobPub:
    - About: ojobpub/index.md
    - Format: ojobpub/format.md
    - Schema: ojobpub/schema.md

  - letsemploy.org: //letsemploy.org

theme:
  name: material
  features:
    - navigation.tabs
    - content.action.edit
    - content.action.view
  font: false
  logo: static/logo_tp.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - minify:
      minify_html: true

copyright: |
  LetsEmploy.org Â© 2025-2026

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/letsemploy/docs

extra_css:
  - stylesheets/extra.css
